services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-be-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    command: >
      sh -c "composer install --no-interaction --optimize-autoloader --no-dev
      && php-fpm"
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/html
    networks:
      - schedule-be-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: schedule-be-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - schedule-be-network

networks:
  schedule-be-network:
    driver: bridge
